In [37]:
# 📦 1. Import Required Libraries
 
import pandas as pd # Data manipulation and analysis
import numpy as np # Numerical operations
import os # Operating system interactions       
import matplotlib.pyplot as plt  # Plotting library for creating static, animated, and interactive visualizations
import seaborn as sns # Statistical data visualization library


# 🧠 These libraries help us handle data and visualize it.

# 📂 2. Load the Excel File
 
df = pd.read_excel("flight_price.xlsx")
# 📄 Loads the dataset into a DataFrame called df.
#👀 3. View the First Few Rows
df.head()
    # | Airline     | Date of Journey | Source   | Destination | Route                 | Departure Time | Arrival Time | Duration | Stops    | Additional Info | Price (₹) |
# | - | ----------- | --------------- | -------- | ----------- | --------------------- | -------------- | ------------ | -------- | -------- | --------------- | --------- |
# | 0 | IndiGo      | 24/03/2019      | Banglore | New Delhi   | BLR → DEL             | 22:20          | 01:10 22 Mar | 2h 50m   | non-stop | No info         | 3,897     |
# | 1 | Air India   | 01/05/2019      | Kolkata  | Banglore    | CCU → IXR → BBI → BLR | 05:50          | 13:15        | 7h 25m   | 2 stops  | No info         | 7,662     |
# | 2 | Jet Airways | 09/06/2019      | Delhi    | Cochin      | DEL → LKO → BOM → COK | 09:25          | 04:25 10 Jun | 19h      | 2 stops  | No info         | 13,882    |
# | 3 | IndiGo      | 12/05/2019      | Kolkata  | Banglore    | CCU → NAG → BLR       | 18:05          | 23:30        | 5h 25m   | 1 stop   | No info         | 6,218     |
# | 4 | IndiGo      | 01/03/2019      | Banglore | New Delhi   | BLR → NAG → DEL       | 16:50          | 21:35        | 4h 45m   | 1 stop   | No info         | 13,302    |

# 🧾 4. Check Data Info
 
df.info()
 #   Column           Non-Null Count  Dtype 
# ---  ------           --------------  ----- 
#  0   Airline          10683 non-null  object
#  1   Date_of_Journey  10683 non-null  object
#  2   Source           10683 non-null  object
#  3   Destination      10683 non-null  object
#  4   Route            10682 non-null  object
#  5   Dep_Time         10683 non-null  object
#  6   Arrival_Time     10683 non-null  object
#  7   Duration         10683 non-null  object
#  8   Total_Stops      10682 non-null  object
#  9   Additional_Info  10683 non-null  object
#  10  Price            10683 non-null  int64 

# 📊 Shows:
# Number of rows & columns
# Data types (e.g., object, int)
# Non-null values

# 🔢 5. Describe Numeric Data
 
df.describe()
# | Statistic                | Price (₹) |
# | ------------------------ | --------- |
# | **Count**                | 10,683    |
# | **Mean**                 | 9,087.06  |
# | **Standard Deviation**   | 4,611.36  |
# | **Minimum**              | 1,759     |
# | **25th Percentile (Q1)** | 5,277     |
# | **Median (Q2)**          | 8,372     |
# | **75th Percentile (Q3)** | 12,373    |
# | **Maximum**              | 79,512    |

# 📉 Gives stats like mean, std, min, max for numerical columns.

# 📅 6. Extract Day, Month, Year from Date_of_Journey

# Convert the 'Date_of_Journey' column to datetime format
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], format='%d/%m/%Y')

# Create new columns for day, month, and year
df['Journey_Day'] = df['Date_of_Journey'].dt.day
df['Journey_Month'] = df['Date_of_Journey'].dt.month
df['Journey_Year'] = df['Date_of_Journey'].dt.year

# Optional: Check the new columns
df[['Date_of_Journey', 'Journey_Day', 'Journey_Month', 'Journey_Year']].head()
# | # | Date of Journey | Day | Month | Year |
# | - | --------------- | --- | ----- | ---- |
# | 0 | 2019-03-24      | 24  | March | 2019 |
# | 1 | 2019-05-01      | 01  | May   | 2019 |
# | 2 | 2019-06-09      | 09  | June  | 2019 |
# | 3 | 2019-05-12      | 12  | May   | 2019 |
# | 4 | 2019-03-01      | 01  | March | 2019 |

df.head()
# | # | Airline     | Date of Journey | Journey_Day | Journey_Month | Journey_Year | Source   | Destination | Route         | Departure | Arrival      | Duration | Stops    | Additional Info | Price (₹) |
# | - | ----------- | --------------- | ----------- | --------------| -------------|----------|-------------|---------------|-----------|--------------|----------|----------|------------------|-----------|
# | 0 | IndiGo      | 2019-03-24      | 24          | March         | 2019         | Banglore | New Delhi   | BLR → DEL     | 22:20     | 01:10 22 Mar | 2h 50m   | non-stop | No info         | 3,897     |
# | 1 | Air India   | 2019-05-01      | 01          | May           | 2019         | Kolkata  | Banglore    | CCU → IXR → BB| 05:50     | 13:15        | 7h 25m   | 2 stops | No info         | 7,662     |
# | 2 | Jet Airways | 2019-06-09      | 09          | June          | 2019         | Delhi    | Cochin      | DEL → LKO → BO| 09:25     | 04:25 10 Jun | 19h      | 2 stops | No info         | 13,882    |
# | 3 | IndiGo      | 2019-05-12      | 12          | May           | 2019         | Kolkata  | Banglore    | CCU → NAG → BL| 18:05     | 23:30        | 5h 25m   | 1 stop  | No info         | 6,218     |
# | 4 | IndiGo      | 2019-03-01      | 01          | March         | 2019         | Banglore | New Delhi   | BLR → NAG → D | 16:50     | 21:35        | 4h 45m   | 1 stop  | No info         | 13,302    |

df.info()
# 🔁 7. Convert to Integer

df['Journey_Day'] = df['Journey_Day'].astype(int)
df['Journey_Month'] = df['Journey_Month'].astype(int)
df['Journey_Year'] = df['Journey_Year'].astype(int)

# Optional: Check data types to confirm
print(df[['Journey_Day', 'Journey_Month', 'Journey_Year']].dtypes)
# Journey_Day      int32
# Journey_Month    int32
# Journey_Year     int32

# ❌ 8. Drop Date_of_Journey

df.drop(columns=['Date_of_Journey'], inplace=True)

# Optional: Check if the column is removed
print(df.columns)
# Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
#        'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Journey_Day',
#        'Journey_Month', 'Journey_Year'],
#       dtype='object')

df.head()
#    Airline      Source    Destination  Route                  Dep_Time  Arrival_Time   Duration  Total_Stops  Additional_Info  Price  Journey_Day  Journey_Month  Journey_Year
# 0  IndiGo      Banglore  New Delhi    BLR → DEL               22:20    01:10 22 Mar   2h 50m   non-stop    No info          3897   24           3              2019
# 1  Air India   Kolkata   Banglore    CCU → IXR → BBI → BLR    05:50    13:15          7h 25m   2 stops    No info          7662   1            5              2019
# 2  Jet Airways Delhi     Cochin      DEL → LKO → BOM → COK    09:25    04:25 10 Jun   19h      2 stops    No info          13882  9            6              2019
# 3  IndiGo      Kolkata   Banglore    CCU → NAG → BLR          18:05    23:30          5h 25m   1 stop     No info          6218   12           5              2019
# 4  IndiGo      Banglore  New Delhi   BLR → NAG → DEL          16:50    21:35          4h 45m   1 stop     No info          13302  1            3              2019

# ⌚ 9. Extract Arrival_Hour and Arrival_Minute

# Split 'Arrival_Time' into hour and minute
df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_Minute'] = df['Arrival_Time'].str.split(':').str[1].str[:2].astype(int)

# Optional: Check the new columns
print(df[['Arrival_Time', 'Arrival_Hour', 'Arrival_Minute']].head())
#    Arrival_Time  Arrival_Hour  Arrival_Minute
# 0  01:10 22 Mar             1              10
# 1         13:15            13              15
# 2  04:25 10 Jun             4              25
# 3         23:30            23              30
# 4         21:35            21              35

# 🛫 10. Extract Departure_Hour and Departure_Minute

# Split 'Dep_Time' into hour and minute
df['Departure_Hour'] = df['Dep_Time'].str.split(':').str[0].astype(int)
df['Departure_Minute'] = df['Dep_Time'].str.split(':').str[1].astype(int)

# Optional: Check the new columns
print(df[['Dep_Time', 'Departure_Hour', 'Departure_Minute']].head())
#     Dep_Time  Departure_Hour  Departure_Minute
# 0    22:20              22                20
# 1    05:50               5                50
# 2    09:25               9                25
# 3    18:05              18                 5
# 4    16:50              16                50

# 🔢 11. Convert Total_Stops to Numbers (Ordinal)

# Map the 'Total_Stops' column to numeric values
stops_mapping = {
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4
}

df['Total_Stops'] = df['Total_Stops'].map(stops_mapping)

# Optional: Check for any remaining missing values (e.g., if there were NaNs or unusual values)
print(df['Total_Stops'].unique())

# 🔢 11. Convert Total_Stops to Numbers (Ordinal)

# Map the 'Total_Stops' column to numeric values
stops_mapping = {
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4,
    np.nan: np.nan  # Keep NaN values as is
}

df['Total_Stops'] = df['Total_Stops'].map(stops_mapping)

# Optional: Check for any remaining missing values (e.g., if there were NaNs or unusual values)
print(df['Total_Stops'].unique())
# [ 0.  2.  1.  3. nan  4.]
# 🗑️ 12. Drop Route
df.drop(columns=['Route'], inplace=True)
# Optional: Check if the column is removed
print(df.columns)
# Index(['Airline', 'Source', 'Destination', 'Dep_Time', 'Arrival_Time',
#        'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Journey_Day',
#        'Journey_Month', 'Journey_Year', 'Arrival_Hour', 'Arrival_Minute',
#        'Departure_Hour', 'Departure_Minute'],
#       dtype='object')

# ⏱️ 13. Split Duration into Hours and Minutes
df['Total_Stops'].unique() 
# Some durations are like '2h 50m', some like '19h', some like '50m'
def extract_duration(duration):
    hours = 0
    minutes = 0
    if 'h' in duration:
        hours = int(duration.split('h')[0].strip())
        if 'm' in duration:
            minutes = int(duration.split('h')[1].replace('m', '').strip())
    else:
        if 'm' in duration:
            minutes = int(duration.replace('m', '').strip())
    return hours, minutes

# Apply the function to each row
df['Duration_Hours'] = df['Duration'].apply(lambda x: extract_duration(x)[0])
df['Duration_Minutes'] = df['Duration'].apply(lambda x: extract_duration(x)[1])

# Optional: Check the new columns
print(df[['Duration', 'Duration_Hours', 'Duration_Minutes']].head())
# Duration  Duration_Hours  Duration_Minutes
# 0   2h 50m               2                50
# 1   7h 25m               7                25
# 2      19h              19                 0
# 3   5h 25m               5                25
# 4   4h 45m               4                45

df.head()
#| # | Airline     | Source   | Destination | Dep\_Time | Arrival_Time | Duration | Total_Stops | Additional_Info | Price | Journey_Day | Journey_Month | Journey_Year | Arrival_Hour | Arrival_Minute | Departure_Hour | Departure_Minute | Duration_Hours | Duration_Minutes |
# | - | ----------- | -------- | ----------- | --------- | ------------- | -------- | ------------ | ---------------- | ----- | ------------ | -------------- | ------------- | ------------- | --------------- | --------------- | ----------------- | --------------- | ----------------- |
# | 0 | IndiGo      | Banglore | New Delhi   | 22:20     | 01:10 22 Mar  | 2h 50m   | NaN          | No info          | 3897  | 24           | 3              | 2019          | 1             | 10              | 22              | 20                | 2               | 50                |
# | 1 | Air India   | Kolkata  | Banglore    | 05:50     | 13:15         | 7h 25m   | NaN          | No info          | 7662  | 1            | 5              | 2019          | 13            | 15              | 5               | 50                | 7               | 25                |
# | 2 | Jet Airways | Delhi    | Cochin      | 09:25     | 04:25 10 Jun  | 19h      | NaN          | No info          | 13882 | 9            | 6              | 2019          | 4             | 25              | 9               | 25                | 19              | 0                 |
# | 3 | IndiGo      | Kolkata  | Banglore    | 18:05     | 23:30         | 5h 25m   | NaN          | No info          | 6218  | 12           | 5              | 2019          | 23            | 30              | 18              | 5                 | 5               | 25                |
# | 4 | IndiGo      | Banglore | New Delhi   | 16:50     | 21:35         | 4h 45m   | NaN          | No info          | 13302 | 1            | 3              | 2019          | 21            | 35              | 16              | 50                | 4               | 45                |
df.info()
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 10683 entries, 0 to 10682
# Data columns (total 18 columns):
#  #   Column            Non-Null Count  Dtype  
# ---  ------            --------------  -----  
#  0   Airline           10683 non-null  object 
#  1   Source            10683 non-null  object 
#  2   Destination       10683 non-null  object 
#  3   Dep_Time          10683 non-null  object 
#  4   Arrival_Time      10683 non-null  object 
#  5   Duration          10683 non-null  object 
#  6   Total_Stops       0 non-null      float64
#  7   Additional_Info   10683 non-null  object 
#  8   Price             10683 non-null  int64  
#  9   Journey_Day       10683 non-null  int32  
#  10  Journey_Month     10683 non-null  int32  
#  11  Journey_Year      10683 non-null  int32  
#  12  Arrival_Hour      10683 non-null  int32  
#  13  Arrival_Minute    10683 non-null  int32  
#  14  Departure_Hour    10683 non-null  int32  
#  15  Departure_Minute  10683 non-null  int32  
#  16  Duration_Hours    10683 non-null  int64  
#  17  Duration_Minutes  10683 non-null  int64  
# dtypes: float64(1), int32(7), int64(3), object(7)
# memory usage: 1.2+ MB
df.head()

# 🧩 14. One‑Hot Encode Airline, Source, Destination, Additional_Info

# Perform one-hot encoding on categorical columns
df = pd.get_dummies(df, columns=['Airline', 'Source', 'Destination', 'Additional_Info'], drop_first=True)

# Optional: Check the new columns
print(df.columns)
# Index(['Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops', 'Price',
#        'Journey_Day', 'Journey_Month', 'Journey_Year', 'Arrival_Hour',
#        'Arrival_Minute', 'Departure_Hour', 'Departure_Minute',
#        'Duration_Hours', 'Duration_Minutes', 'Airline_Air Asia',
#        'Airline_Air India', 'Airline_GoAir', 'Airline_IndiGo',
#        'Airline_Jet Airways', 'Airline_Jet Airways Business',
#        'Airline_Multiple carriers',
#        'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
#        'Airline_Trujet', 'Airline_Vistara', 'Airline_Vistara Premium economy',
#        'Source_Banglore', 'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
#        'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
#        'Destination_Delhi', 'Destination_Hyderabad', 'Destination_Kolkata',
#        'Destination_New Delhi', 'Additional_Info_1 Long layover',
#        'Additional_Info_1 Short layover', 'Additional_Info_2 Long layover',
#        'Additional_Info_Business class', 'Additional_Info_Change airports',
#        'Additional_Info_In-flight meal not included',
#        'Additional_Info_No Info',
#        'Additional_Info_No check-in baggage included',
#        'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
#       dtype='object')

# Convert all categorical and object features into numerical features

# List of columns with object dtype (categorical features)
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
# Exclude columns that are already numeric or not needed for encoding
# (If you want to keep 'Dep_Time', 'Arrival_Time', 'Duration', drop them from cat_cols)
cat_cols = [col for col in cat_cols if col not in ['Dep_Time', 'Arrival_Time', 'Duration']]
# One-hot encode all remaining categorical columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)
# Optional: Check the new columns and data types
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  datetime64[ns]
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Journey_Day      10683 non-null  int32
 12  Journey_Month    10683 non-null  int32
 13  Journey_Year     10683 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(1), object(9)
memory usage: 1.0+ MB
Journey_Day      int32
Journey_Month    int32
Journey_Year     int32
dtype: object
Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Journey_Day',
       'Journey_Month', 'Journey_Year'],
      dtype='object')
   Arrival_Time  Arrival_Hour  Arrival_Minute
0  01:10 22 Mar             1              10
1         13:15            13              15
2  04:25 10 Jun             4              25
3         23:30            23              30
4         21:35            21              35
  Dep_Time  Departure_Hour  Departure_Minute
0    22:20              22                20
1    05:50               5                50
2    09:25               9                25
3    18:05              18                 5
4    16:50              16                50
[ 0.  2.  1.  3. nan  4.]
[nan]
Index(['Airline', 'Source', 'Destination', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Journey_Day',
       'Journey_Month', 'Journey_Year', 'Arrival_Hour', 'Arrival_Minute',
       'Departure_Hour', 'Departure_Minute'],
      dtype='object')
  Duration  Duration_Hours  Duration_Minutes
0   2h 50m               2                50
1   7h 25m               7                25
2      19h              19                 0
3   5h 25m               5                25
4   4h 45m               4                45
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  object
 1   Source            10683 non-null  object
 2   Destination       10683 non-null  object
 3   Dep_Time          10683 non-null  object
 4   Arrival_Time      10683 non-null  object
 5   Duration          10683 non-null  object
 6   Total_Stops       0 non-null      float64
 7   Additional_Info   10683 non-null  object
 8   Price             10683 non-null  int64
 9   Journey_Day       10683 non-null  int32
 10  Journey_Month     10683 non-null  int32
 11  Journey_Year      10683 non-null  int32
 12  Arrival_Hour      10683 non-null  int32
 13  Arrival_Minute    10683 non-null  int32
 14  Departure_Hour    10683 non-null  int32
 15  Departure_Minute  10683 non-null  int32
 16  Duration_Hours    10683 non-null  int64
 17  Duration_Minutes  10683 non-null  int64
dtypes: float64(1), int32(7), int64(3), object(7)
memory usage: 1.2+ MB
Index(['Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops', 'Price',
       'Journey_Day', 'Journey_Month', 'Journey_Year', 'Arrival_Hour',
       'Arrival_Minute', 'Departure_Hour', 'Departure_Minute',
       'Duration_Hours', 'Duration_Minutes', 'Airline_Air India',
       'Airline_GoAir', 'Airline_IndiGo', 'Airline_Jet Airways',
       'Airline_Jet Airways Business', 'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara', 'Airline_Vistara Premium economy',
       'Source_Chennai', 'Source_Delhi', 'Source_Kolkata', 'Source_Mumbai',
       'Destination_Cochin', 'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_New Delhi',
       'Additional_Info_1 Short layover', 'Additional_Info_2 Long layover',
       'Additional_Info_Business class', 'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype='object')
Dep_Time                                         object
Arrival_Time                                     object
Duration                                         object
Total_Stops                                     float64
Price                                             int64
Journey_Day                                       int32
Journey_Month                                     int32
Journey_Year                                      int32
Arrival_Hour                                      int32
Arrival_Minute                                    int32
Departure_Hour                                    int32
Departure_Minute                                  int32
Duration_Hours                                    int64
Duration_Minutes                                  int64
Airline_Air India                                  bool
Airline_GoAir                                      bool
Airline_IndiGo                                     bool
Airline_Jet Airways                                bool
Airline_Jet Airways Business                       bool
Airline_Multiple carriers                          bool
Airline_Multiple carriers Premium economy          bool
Airline_SpiceJet                                   bool
Airline_Trujet                                     bool
Airline_Vistara                                    bool
Airline_Vistara Premium economy                    bool
Source_Chennai                                     bool
Source_Delhi                                       bool
Source_Kolkata                                     bool
Source_Mumbai                                      bool
Destination_Cochin                                 bool
Destination_Delhi                                  bool
Destination_Hyderabad                              bool
Destination_Kolkata                                bool
Destination_New Delhi                              bool
Additional_Info_1 Short layover                    bool
Additional_Info_2 Long layover                     bool
Additional_Info_Business class                     bool
Additional_Info_Change airports                    bool
Additional_Info_In-flight meal not included        bool
Additional_Info_No Info                            bool
Additional_Info_No check-in baggage included       bool
Additional_Info_No info                            bool
Additional_Info_Red-eye flight                     bool
dtype: object